### ISSUE TITLE
How Could I add this calculator to my website

### ISSUE THREAD

**Issue by douglasroz** [apknusel/Infinite_Campus_GPA_Calculator#1]
Hi,

I want to know How Could I add this [GPA on Infinite Campus](https://dottrusty.com/how-to-find-your-gpa-on-infinite-campus/) calculator to my website

**Comment by apknusel** [comment]
The tool is quite outdated and

**Comment by apknusel** [comment]
The tool is not updated and was explicitly made for Infinite Campus. I don't know how you would incorporate this into your website or what you mean by this. The extension scrapes some information from the infinite campus website such as grades and uses a simple GPA formula to calculate the GPA.

**Comment by douglasroz** [comment]
ok I understand
